export const DOG_BREEDS = [
  "Affenpinscher", "Afghan Hound", "Airedale Terrier", "Akita", "Akita Inu", "Alaskan Klee Kai", "Alaskan Malamute",
  "American Bulldog", "American Bully", "American Cocker Spaniel", "American Eskimo Dog", "American Foxhound",
  "American Hairless Terrier", "American Leopard Hound", "American Pit Bull Terrier", "American Staffordshire Terrier",
  "American Water Spaniel", "Anatolian Shepherd", "Appenzeller Sennenhund", "Australian Cattle Dog",
  "Australian Kelpie", "Australian Shepherd", "Australian Stumpy Tail Cattle Dog", "Australian Terrier",
  "Azawakh", "Barbet", "Basenji", "Basset Fauve de Bretagne", "Basset Hound", "Bavarian Mountain Hound",
  "Beagle", "Beagle Harrier", "Bearded Collie", "Beauceron", "Bedlington Terrier",
  "Belgian Laekenois", "Belgian Malinois", "Belgian Sheepdog", "Belgian Tervuren", "Bergamasco Sheepdog",
  "Berger Picard", "Bernese Mountain Dog", "Bichon Frise", "Biewer Terrier", "Black and Tan Coonhound",
  "Black Mouth Cur", "Black Russian Terrier", "Bloodhound", "Blue Lacy", "Bluetick Coonhound",
  "Boerboel", "Bolognese", "Border Collie", "Border Terrier", "Borzoi", "Boston Terrier",
  "Bouvier des Flandres", "Boxer", "Boykin Spaniel", "Bracco Italiano", "Braque du Bourbonnais",
  "Briard", "Brittany", "Broholmer", "Brussels Griffon", "Bull Terrier", "Bulldog", "Bullmastiff",
  "Cairn Terrier", "Canaan Dog", "Cane Corso", "Cardigan Welsh Corgi", "Carolina Dog",
  "Catahoula Leopard Dog", "Caucasian Shepherd Dog", "Cavalier King Charles Spaniel",
  "Central Asian Shepherd Dog", "Cesky Terrier", "Chesapeake Bay Retriever", "Chihuahua",
  "Chinese Crested", "Chinese Shar-Pei", "Chinook", "Chow Chow", "Cirneco dell'Etna",
  "Clumber Spaniel", "Cocker Spaniel", "Collie", "Coton de Tulear", "Croatian Sheepdog",
  "Curly-Coated Retriever", "Czechoslovakian Vlcak", "Dachshund", "Dalmatian", "Dandie Dinmont Terrier",
  "Danish-Swedish Farmdog", "Deutscher Wachtelhund", "Doberman Pinscher", "Dogo Argentino", "Dogue de Bordeaux",
  "Drentsche Patrijshond", "Drever", "Dutch Shepherd", "English Bulldog", "English Cocker Spaniel",
  "English Foxhound", "English Setter", "English Springer Spaniel", "English Toy Spaniel",
  "Entlebucher Mountain Dog", "Estrela Mountain Dog", "Eurasier", "Field Spaniel",
  "Finnish Lapphund", "Finnish Spitz", "Flat-Coated Retriever", "Fox Terrier", "French Bulldog",
  "French Spaniel", "German Longhaired Pointer", "German Pinscher", "German Shepherd",
  "German Shorthaired Pointer", "German Spitz", "German Wirehaired Pointer", "Giant Schnauzer",
  "Glen of Imaal Terrier", "Golden Retriever", "Gordon Setter", "Grand Basset Griffon Vendeen",
  "Great Dane", "Great Pyrenees", "Greater Swiss Mountain Dog", "Greyhound", "Hamiltonstovare",
  "Hanoverian Scenthound", "Harrier", "Havanese", "Hokkaido", "Hovawart",
  "Ibizan Hound", "Icelandic Sheepdog", "Irish Red and White Setter", "Irish Setter", "Irish Terrier",
  "Irish Water Spaniel", "Irish Wolfhound", "Italian Greyhound", "Jagdterrier", "Jack Russell Terrier",
  "Japanese Chin", "Japanese Spitz", "Japanese Terrier", "Jindo", "Kai Ken",
  "Karelian Bear Dog", "Keeshond", "Kerry Blue Terrier", "King Charles Spaniel", "Kishu Ken",
  "Komondor", "Kooikerhondje", "Korean Jindo", "Kromfohrlander", "Kuvasz",
  "Labrador Retriever", "Lagotto Romagnolo", "Lakeland Terrier", "Lancashire Heeler",
  "Lapponian Herder", "Leonberger", "Lhasa Apso", "Lowchen",
  "Maltese", "Manchester Terrier", "Maremma Sheepdog", "Mastiff", "Miniature American Shepherd",
  "Miniature Bull Terrier", "Miniature Pinscher", "Miniature Poodle", "Miniature Schnauzer",
  "Mountain Cur", "Mudi", "Neapolitan Mastiff", "Newfoundland", "Norfolk Terrier",
  "Norrbottenspets", "Norwegian Buhund", "Norwegian Elkhound", "Norwegian Lundehund", "Norwich Terrier",
  "Nova Scotia Duck Tolling Retriever", "Old English Sheepdog", "Otterhound",
  "Papillon", "Parson Russell Terrier", "Pekingese", "Pembroke Welsh Corgi", "Perro de Presa Canario",
  "Peruvian Inca Orchid", "Petit Basset Griffon Vendeen", "Pharaoh Hound", "Plott Hound",
  "Pointer", "Polish Lowland Sheepdog", "Pomeranian", "Poodle", "Porcelaine",
  "Portuguese Podengo", "Portuguese Pointer", "Portuguese Sheepdog", "Portuguese Water Dog",
  "Pudelpointer", "Pug", "Puli", "Pumi", "Pyrenean Mastiff", "Pyrenean Shepherd",
  "Rafeiro do Alentejo", "Rat Terrier", "Redbone Coonhound", "Rhodesian Ridgeback",
  "Romanian Mioritic Shepherd Dog", "Rottweiler", "Russell Terrier", "Russian Toy",
  "Saint Bernard", "Saluki", "Samoyed", "Schapendoes", "Schipperke", "Scottish Deerhound",
  "Scottish Terrier", "Sealyham Terrier", "Segugio Italiano", "Shetland Sheepdog",
  "Shiba Inu", "Shih Tzu", "Shikoku", "Siberian Husky", "Silken Windhound",
  "Silky Terrier", "Skye Terrier", "Sloughi", "Slovakian Wirehaired Pointer",
  "Slovensky Cuvac", "Slovensky Kopov", "Small Munsterlander Pointer",
  "Smooth Fox Terrier", "Soft Coated Wheaten Terrier", "Spanish Mastiff", "Spanish Water Dog",
  "Spinone Italiano", "Stabyhoun", "Staffordshire Bull Terrier", "Standard Poodle",
  "Standard Schnauzer", "Sussex Spaniel", "Swedish Lapphund", "Swedish Vallhund",
  "Taiwan Dog", "Teddy Roosevelt Terrier", "Thai Ridgeback", "Tibetan Mastiff",
  "Tibetan Spaniel", "Tibetan Terrier", "Tornjak", "Tosa", "Toy Fox Terrier",
  "Toy Manchester Terrier", "Toy Poodle", "Transylvanian Hound", "Treeing Tennessee Brindle",
  "Treeing Walker Coonhound", "Vizsla", "Volpino Italiano", "Weimaraner",
  "Welsh Springer Spaniel", "Welsh Terrier", "West Highland White Terrier", "Wetterhoun",
  "Whippet", "Wire Fox Terrier", "Wirehaired Pointing Griffon", "Wirehaired Vizsla",
  "Working Kelpie", "Xoloitzcuintli", "Yakutian Laika", "Yorkshire Terrier",
  "Mixed Breed",
  "Mixed - Labradoodle (Labrador + Poodle)",
  "Mixed - Goldendoodle (Golden Retriever + Poodle)",
  "Mixed - Cockapoo (Cocker Spaniel + Poodle)",
  "Mixed - Maltipoo (Maltese + Poodle)",
  "Mixed - Cavapoo (Cavalier King Charles + Poodle)",
  "Mixed - Pomsky (Pomeranian + Husky)",
  "Mixed - Puggle (Pug + Beagle)",
  "Mixed - Schnoodle (Schnauzer + Poodle)",
  "Mixed - Yorkipoo (Yorkshire Terrier + Poodle)",
  "Mixed - Sheepadoodle (Old English Sheepdog + Poodle)",
  "Mixed - Bernedoodle (Bernese Mountain Dog + Poodle)",
  "Mixed - Aussiedoodle (Australian Shepherd + Poodle)",
  "Mixed - Cavachon (Cavalier King Charles + Bichon Frise)",
  "Mixed - Morkie (Maltese + Yorkshire Terrier)",
  "Mixed - Shorkie (Shih Tzu + Yorkshire Terrier)",
  "Mixed - Corgipoo (Corgi + Poodle)",
  "Mixed - Boxerdoodle (Boxer + Poodle)",
  "Mixed - Shihpoo (Shih Tzu + Poodle)",
  "Mixed - Poochon (Poodle + Bichon Frise)",
  "Mixed - Peekapoo (Pekingese + Poodle)",
  "Mixed - Chipoo (Chihuahua + Poodle)",
  "Mixed - Huskydoodle (Husky + Poodle)",
  "Mixed - Pitsky (Pitbull + Husky)",
  "Mixed - Goberian (Golden Retriever + Husky)",
  "Mixed - Shepsky (German Shepherd + Husky)",
  "Mixed - Pomchi (Pomeranian + Chihuahua)",
  "Mixed - Chorkie (Chihuahua + Yorkshire Terrier)",
  "Mixed - Chiweenie (Chihuahua + Dachshund)",
  "Mixed - Dorkie (Dachshund + Yorkshire Terrier)",
  "Mixed - Frenchton (French Bulldog + Boston Terrier)",
  "Mixed - Bugg (Boston Terrier + Pug)",
  "Mixed - Chug (Chihuahua + Pug)",
  "Mixed - Jug (Jack Russell + Pug)",
  "Mixed - Pugapoo (Pug + Poodle)",
  "Mixed - Beaglier (Beagle + Cavalier King Charles)",
  "Mixed - Cavapoochon (Cavalier + Poodle + Bichon)",
  "Mixed - Springerdoodle (Springer Spaniel + Poodle)",
  "Mixed - Whoodle (Wheaten Terrier + Poodle)",
  "Mixed - Bordoodle (Border Collie + Poodle)",
  "Mixed - Shepadoodle (German Shepherd + Poodle)",
  "Mixed - Rottle (Rottweiler + Poodle)",
  "Mixed - Mastidoodle (Mastiff + Poodle)",
  "Mixed - Newfypoo (Newfoundland + Poodle)",
  "Mixed - Pyredoodle (Great Pyrenees + Poodle)",
  "Mixed - Saint Berdoodle (Saint Bernard + Poodle)",
  "Mixed - Irish Doodle (Irish Setter + Poodle)",
  "Mixed - Scoodle (Scottish Terrier + Poodle)",
  "Mixed - Westiepoo (West Highland Terrier + Poodle)",
  "Mixed - Doxiepoo (Dachshund + Poodle)",
  "Mixed - Bassetoodle (Basset Hound + Poodle)",
  "Mixed - Boxador (Boxer + Labrador)",
  "Mixed - Bullador (Bulldog + Labrador)",
  "Mixed - Chabrador (Chow Chow + Labrador)",
  "Mixed - Dalmador (Dalmatian + Labrador)",
  "Mixed - German Sheprador (German Shepherd + Labrador)",
  "Mixed - Goldador (Golden Retriever + Labrador)",
  "Mixed - Huskador (Husky + Labrador)",
  "Mixed - Rottador (Rottweiler + Labrador)",
  "Mixed - Shepradors (German Shepherd + Labrador)",
  "Shepherd Mix", "Retriever Mix", "Terrier Mix", "Hound Mix",
  "Spaniel Mix", "Collie Mix", "Husky Mix", "Pitbull Mix",
  "Rottweiler Mix", "Beagle Mix", "Poodle Mix", "Bulldog Mix",
  "Mastiff Mix", "Pointer Mix", "Setter Mix", "Schnauzer Mix",
  "Others (Specify Below)",
];
